# Generated by Django 2.0.2 on 2018-02-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMetricReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.DataSource')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Location'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.WeatherMetric'),
        ),
    ]
