# Generated by Django 2.0.2 on 2018-02-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20180225_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathermetricreading',
            options={'ordering': ['year', 'month']},
        ),
    ]
